name: family_history

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    hostname: database
    container_name: database
    image: postgres:17-bookworm
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    hostname: cache
    container_name: cache
    image: redis:8.0.3-bookworm
    volumes:
      - ./cache:/usr/local/etc/redis
    restart: always

  migrations_generate:
    container_name: migrations_generate
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - backend