"""added relationship users in budget models

Revision ID: 66740abd024d
Revises: 53ea6477450c
Create Date: 2025-07-18 15:43:03.467232

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '66740abd024d'
down_revision: Union[str, None] = '53ea6477450c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'expenses',
        sa.Column(
            'user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f('fk_expenses_user_id_users'),
        'expenses',
        'users',
        ['user_id'],
        ['id'],
    )
    op.add_column(
        'expenses_categories',
        sa.Column(
            'user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f('fk_expenses_categories_user_id_users'),
        'expenses_categories',
        'users',
        ['user_id'],
        ['id'],
    )
    op.add_column(
        'incomes',
        sa.Column(
            'user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f('fk_incomes_user_id_users'),
        'incomes',
        'users',
        ['user_id'],
        ['id'],
    )
    op.add_column(
        'incomes_categories',
        sa.Column(
            'user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f('fk_incomes_categories_user_id_users'),
        'incomes_categories',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_incomes_categories_user_id_users'),
        'incomes_categories',
        type_='foreignkey',
    )
    op.drop_column('incomes_categories', 'user_id')
    op.drop_constraint(
        op.f('fk_incomes_user_id_users'),
        'incomes',
        type_='foreignkey',
    )
    op.drop_column('incomes', 'user_id')
    op.drop_constraint(
        op.f('fk_expenses_categories_user_id_users'),
        'expenses_categories',
        type_='foreignkey',
    )
    op.drop_column('expenses_categories', 'user_id')
    op.drop_constraint(
        op.f('fk_expenses_user_id_users'),
        'expenses',
        type_='foreignkey',
    )
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
