"""added relationship users in updated data in models

Revision ID: 2cba25e79c25
Revises: 66740abd024d
Create Date: 2025-07-21 14:28:46.261683

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cba25e79c25'
down_revision: Union[str, None] = '66740abd024d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'expenses',
        sa.Column(
            'updated_user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f('fk_expenses_updated_user_id_users'),
        'expenses',
        'users',
        ['updated_user_id'],
        ['id'],
    )
    op.add_column(
        'expenses_categories',
        sa.Column(
            'updated_user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f('fk_expenses_categories_updated_user_id_users'),
        'expenses_categories',
        'users',
        ['updated_user_id'],
        ['id'],
    )
    op.add_column(
        'incomes',
        sa.Column(
            'updated_user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f('fk_incomes_updated_user_id_users'),
        'incomes',
        'users',
        ['updated_user_id'],
        ['id'],
    )
    op.add_column(
        'incomes_categories',
        sa.Column(
            'updated_user_id',
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f('fk_incomes_categories_updated_user_id_users'),
        'incomes_categories',
        'users',
        ['updated_user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_incomes_categories_updated_user_id_users'),
        'incomes_categories',
        type_='foreignkey',
    )
    op.drop_column('incomes_categories', 'updated_user_id')
    op.drop_constraint(
        op.f('fk_incomes_updated_user_id_users'), 'incomes', type_='foreignkey'
    )
    op.drop_column('incomes', 'updated_user_id')
    op.drop_constraint(
        op.f('fk_expenses_categories_updated_user_id_users'),
        'expenses_categories',
        type_='foreignkey',
    )
    op.drop_column('expenses_categories', 'updated_user_id')
    op.drop_constraint(
        op.f('fk_expenses_updated_user_id_users'),
        'expenses',
        type_='foreignkey',
    )
    op.drop_column('expenses', 'updated_user_id')
    # ### end Alembic commands ###
